### ISSUE TITLE
one-click install of x/84 to digital ocean

### ISSUE THREAD

**Issue by jquast** [jquast/x84#160]
using https://github.com/seven1m/do-install-button

**Comment by haliphax** [comment]
http://oddnetwork.org/hx/x84-do-install.php

I believe all that's left is a pleasing UI and the ability to select your region for the droplet.

**Comment by haliphax** [comment]
Found a bug with the DO API: if you're a member of any teams, the OAuth workflow gets completely messed up. It doesn't allow you to choose which account you are requesting the OAuth access for. If any account hasn't yet authorized, it will not continue until at least one has been granted, and then it will install to that account. Irritating. :(
