### ISSUE TITLE
AnsiWindow's should *not* take a border into account

### ISSUE THREAD

**Issue by jquast** [jquast/x84#161]
there should be a border=True option. currently there is an implicit border of every window.

I should be able to make a window of height 1 and width 10 that, when .fill()'d, is exactly that.

Unfortunately, we must make a window of height 3 and width 12 -- because an invisible border is contained as a part of all windows, which is seen when one echo's a window.border(). It's an API design issue, I fear that some folks would be impacted, its a 3.0 api thing I guess.

this is especially annoying for ScrollingEditor, which must be a height of 3 and a width + 2, with a ypos and xpos offset by 1

**Comment by haliphax** [comment]
Could this maybe be done with `ypadding` and `xpadding`, or are those for the number of blank spaces between the border and the contents?

**Comment by jquast** [comment]
no, y/xpadding won't help here. It would have to be an API change, so pushed to 3.0 release.

**Comment by haliphax** [comment]
I've changed the AssertionError into a FutureWarning in my ircchat.py rewrite.

**Comment by jquast** [comment]
i removed (commented out?) the futurewarning all together, as there were so many of them now :)

**Comment by haliphax** [comment]
Yeah, that's probably better than having a metric tonne of warning filters littering the codebase for now. Heh.
