### ISSUE TITLE
very small screens cause terrible bugs in some scripts

### ISSUE THREAD

**Issue by jquast** [jquast/x84#171]
- who's online also mishandles small screens, wraps a lot for such little info
- voting results incomprehensible, wraps 3 times per result
- charset needs to show an alternative thing when the art won't fit.
- goodbye.py's "try these fine boards" wraps and looks bad

**Comment by jquast** [comment]
also online.py

     dingo@x/84:: who

```
-8G                                         ▁▁▁
-8G                                   ▁▁▁▁▁ ╲▁╱▁▁▁▁▁
-8G
           -- canceled online.ans, too wide:: 75 --
```

**Comment by ericolito** [comment]
is a if term.width > xx:
    showart()...
enough?

**Comment by ericolito** [comment]
or do i have to try and make everything look good with like 40 columns?

**Comment by jquast** [comment]
its not a problem with showart(), showart handles it. When you declare an 'xpos' to use with term.move() or term.move_x(), you should use ``max(0, <code that finds an xpos)`` to ensure it never becomes 0

**Comment by ericolito** [comment]
Ah yeah so you are refering to the -xx mumbo jumbo that shows up on the screen. I get it.

**Comment by haliphax** [comment]
How about showing a 'block gradient' (i..e, most shaded block, medium shaded block, least shaded block, solid block) next to the prompt in `charset.py` when the screen is too small for the artwork? I can whip that together if we think it's acceptable.

**Comment by jquast** [comment]
too late
