### ISSUE TITLE
sesame.py must be document in docs/

### ISSUE THREAD

**Issue by jquast** [jquast/x84#174]
doors support and sesame configuration **MUST** be documented, it requires reading the source code to configure.

**Comment by tehmaze** [comment]
There is no x84.default section in the documentation yet. Are we adding documentation for all the other default scripts too?

**Comment by jquast** [comment]
not unless their docstrings are more improved, some are pretty great, most are really bad.

would prefer a top-level docs/doors.rst tutorial, like docs/msgnet.rst
