### ISSUE TITLE
Configuring a message network must be documented in docs/

### ISSUE THREAD

**Issue by jquast** [jquast/x84#175]
one should not have to read the API documentation of core engine internals to to figure out how to configure this thing.  This is spread across many pages among 60 when left only for API module-level documentation to describe.

This should be a walkthrough guide in the docs/ folder.

**Comment by haliphax** [comment]
I will tackle this after I get the administration scripts written. I should be able to knock that out today or tomorrow.

**Comment by jquast** [comment]
https://x84.readthedocs.org/en/latest/msgnet.html
