### ISSUE TITLE
workaround syncterm's lying height

### ISSUE THREAD

**Issue by jquast** [jquast/x84#188]
adjust our derivied Terminal, that, when kind = 'ansi' and height is 25 or whatever, to actually report 24, so that we can always write to term.height on all terminals

**Comment by haliphax** [comment]
Hrm. Well, SyncTERM can also have the status bar disabled. However, since it doesn't report its height correctly (and it's even worse over SSH due to libcl), I guess there's no good way around that.

**Comment by jquast** [comment]
on the ~2-3yr-old macbuild i use, it reports the same height whether its enabled or not. I have mine disabled, i recall its enabled by default ... i hope it shouldn't be -2 in such cases

**Comment by haliphax** [comment]
The -2 is excessive, I think, isn't it? Why not -1? It's now 80x23 for SyncTerm, which makes DOS doors screw up (and the term fails to meet the `x84.bbs.door.launch` size restrictions for a DOS door, as well, and apparently it trying to fake 80x25 on 80x23 causes an exception, but that's a separate issue that can be dealt with).
