### ISSUE TITLE
^C, ^R, etc. doesn't work in ircchat.py?

### ISSUE THREAD

**Issue by jquast** [jquast/x84#190]

**Comment by jquast** [comment]
I won't fix this now, its too dangerous.  We need to be able to *print* the control characters, too -- currently we assume *everything is naturally printable* -- irssi would term.reverse('C') for ^C, but to do that with an inputbar will reset its sequence attributes and fuck it all up. So we could display '^C' instead, but we have to return byte \x03, and we have to backspace over '^C' (two characters instead of one), etc.

this is just a major fuck-all mess.  Suggest instead to use pipe codes for input, instead.

**Comment by haliphax** [comment]
Pipe codes would be fine. Do we have any that exist for `bold`, `reverse`, and `underline`?

**Comment by jquast** [comment]
not that i know of, don't know if they exist, either.  the http url i previously referenced (mystic wiki) is dead

**Comment by haliphax** [comment]
Well, we can just let them use what's available to `pipe_decode` for now.

**Comment by haliphax** [comment]
For what it's worth, a previous version worked with ^C, ^R, etc. -- but it did not print the characters. They still came across in the output to IRC, though. Anyhow, I'll take a crack at a `pipe_decode`-like function for use in `ircchat.py`.
