### ISSUE TITLE
nntp interface

### ISSUE THREAD

**Issue by jquast** [jquast/x84#20]
nntp / zeronet /agornet link.

I'm fine with making a simple client UI, like tin. Has anybody written a command-line newsgroup reader for python .. ?

**Comment by haliphax** [comment]
Here's some boilerplate code I found that may be a decent starting point (uses a python NNTP module):

https://mail.python.org/pipermail/tutor/2001-April/005046.html

**Comment by haliphax** [comment]
It may actually be easier to integrate with the Papercut NNTP server: http://pessoal.org/papercut/
