### ISSUE TITLE
chat.py throws exception due to KeyError: 'other_sid'

### ISSUE THREAD

**Issue by megagumbo** [jquast/x84#240]
There seems to be an issue with chat.py as it always throws an exception regarding a KeyError: 'other_sid'. Below I've pasted the debug output of the script:

Mon-02-02 03:10PM INFO   session.py:655 runscript 'chat'
Mon-02-02 03:10PM INFO   session.py:655 megagumbo[telnet-192.168.200.10:52227] runscript 'chat'
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 347, in run
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 347, in run
Mon-02-02 03:10PM ERROR  session.py:373     self.runscript(self._script_stack.pop())
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     self.runscript(self._script_stack.pop())
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "/home/x84/src/x84/x84/x84.ufud.eu/main.py", line 215, in main
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "/home/x84/src/x84/x84/x84.ufud.eu/main.py", line 215, in main
Mon-02-02 03:10PM ERROR  session.py:373     gosub(script)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     gosub(script)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 67, in gosub
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 67, in gosub
Mon-02-02 03:10PM ERROR  session.py:373     return getsession().runscript(script)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     return getsession().runscript(script)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "/home/x84/src/x84/x84/x84.ufud.eu/chat.py", line 342, in main
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "/home/x84/src/x84/x84/x84.ufud.eu/chat.py", line 342, in main
Mon-02-02 03:10PM ERROR  session.py:373     do_hangup(session, other_sid=kwargs['other_sid'])
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     do_hangup(session, other_sid=kwargs['other_sid'])
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373 KeyError: 'other_sid'
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] KeyError: 'other_sid'
Mon-02-02 03:10PM ERROR  session.py:326 resume main after general exception in chat
Mon-02-02 03:10PM ERROR  session.py:326 megagumbo[telnet-192.168.200.10:52227] resume main after general exception in chat
Mon-02-02 03:10PM INFO   session.py:655 runscript 'main'
Mon-02-02 03:10PM INFO   session.py:655 megagumbo[telnet-192.168.200.10:52227] runscript 'main'
Mon-02-02 03:10PM INFO   session.py:655 runscript 'chat'
Mon-02-02 03:10PM INFO   session.py:655 megagumbo[telnet-192.168.200.10:52227] runscript 'chat'
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 347, in run
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 347, in run
Mon-02-02 03:10PM ERROR  session.py:373     self.runscript(self._script_stack.pop())
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     self.runscript(self._script_stack.pop())
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "/home/x84/src/x84/x84/x84.ufud.eu/main.py", line 215, in main
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "/home/x84/src/x84/x84/x84.ufud.eu/main.py", line 215, in main
Mon-02-02 03:10PM ERROR  session.py:373     gosub(script)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     gosub(script)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 67, in gosub
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 67, in gosub
Mon-02-02 03:10PM ERROR  session.py:373     return getsession().runscript(script)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     return getsession().runscript(script)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "x84/bbs/session.py", line 685, in runscript
Mon-02-02 03:10PM ERROR  session.py:373     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     value = module.main(*script.args, **script.kwargs)
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373   File "/home/x84/src/x84/x84/x84.ufud.eu/chat.py", line 342, in main
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]   File "/home/x84/src/x84/x84/x84.ufud.eu/chat.py", line 342, in main
Mon-02-02 03:10PM ERROR  session.py:373     do_hangup(session, other_sid=kwargs['other_sid'])
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227]     do_hangup(session, other_sid=kwargs['other_sid'])
Mon-02-02 03:10PM ERROR  session.py:373 
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] 
Mon-02-02 03:10PM ERROR  session.py:373 KeyError: 'other_sid'
Mon-02-02 03:10PM ERROR  session.py:373 megagumbo[telnet-192.168.200.10:52227] KeyError: 'other_sid'
Mon-02-02 03:10PM ERROR  session.py:326 resume main after general exception in chat
Mon-02-02 03:10PM ERROR  session.py:326 megagumbo[telnet-192.168.200.10:52227] resume main after general exception in chat
Mon-02-02 03:10PM INFO   session.py:655 runscript 'main'
Mon-02-02 03:10PM INFO   session.py:655 megagumbo[telnet-192.168.200.10:52227] runscript 'main'

**Comment by jquast** [comment]
you cannot execute ``chat.py`` directly from ``main.py``, which is what you appear to be doing?

It is executed from the online.py script, and requires arguments such as ``other_sid``

**Comment by megagumbo** [comment]
Ah, okay this explains pretty much everything. Sorry for messing up again with my bog report. I did not inted to annoy the developers. Did this change or was chat.py always called from online.py? Once more sorry for another invalid bug report ... I promise to look closer next time!

**Comment by jquast** [comment]
it changed.   chat.py used to be a group chat program, now it is split-screen chat.

**Comment by megagumbo** [comment]
Ah, so this is the reason I still had it as 'main' script in my lightbar_main.py - I must admit I have been a little out of touch with the changes.
