### ISSUE TITLE
quick login default response?

### ISSUE THREAD

**Issue by nolageek** [jquast/x84#242]
Should quick login have a default response, similar to oneliners' "say something? [yN]?

**Comment by jquast** [comment]
i don't know, should it? :)

**Comment by jesseward** [comment]
@nolageek added a default in https://github.com/jesseward/x84/commit/d75f2603a84929b99352590f1291aacc4e7b3712 . I think that functionality is really user (or sysop) preference. Feel free to take the modifications form their for your own implementation.
