### ISSUE TITLE
inaccessible messages included in unread count

### ISSUE THREAD

**Issue by haliphax** [jquast/x84#252]
When showing the count of unread messages, private messages to other users (which the message reader will not show) are included in the total.

Additionally, using 'm' to 'mark all as read' when there are (public) unread messages brings the unread count to 0.

**Comment by jquast** [comment]
code is

https://github.com/jquast/x84/blob/master/x84/default/msgarea.py#L137-164

**Comment by jquast** [comment]
try moving ``all_private = list_privmsgs(None)`` to line 143,
then deleting lines 155, 156,
```
messages['new'] -= all_private
messages['all'] -= all_private
```
then changing all occurrences of ``.update(msg_indicies)`` to ``.update(msg_indicies - all_private)``

**Comment by haliphax** [comment]
I'll give that a shot this week.

**Comment by haliphax** [comment]
Looks like that fix does work. I'm going to ride it out for a day or two and then send a PR.

**Comment by haliphax** [comment]
Hmmm... well, my *own* unread private messages are no longer included in the count. I'll tweak that and test again.

**Comment by jquast** [comment]
tags may also have to be filtered away.  I have tags for messages I can't read.
