### ISSUE TITLE
Who (Splitscreen) Chat bug on ESC

### ISSUE THREAD

**Issue by M-griffin** [jquast/x84#254]
Looks like there is a (who) from main menu issues with the SplitsScreen Chat. ScreenShot: https://dl.dropboxusercontent.com/u/92792939/x84%20chatbug.png    

When i'm in chat,  i Hit ESC,  then it's shows the magenta prompt from main menu, but doesn't redraw the screen, and no commands seem work, so your just stuck.

**Comment by jquast** [comment]
you're not exactly stuck, this is because you do not support the alternate screen sequence

**Comment by M-griffin** [comment]
Ok i'll test and compare this with putty, and also check some other clients.

**Comment by M-griffin** [comment]
Ok, I see, it's not stuck,  that alternate screen sequence expects to the flip to redraw the screen as it was prior to switching.   I'l check some other clients; It might be a good idea for unsupported clients, to re-draw the menu on exiting after the alt screen flip.

**Comment by jquast** [comment]
the only unsupported client i know of is yours

**Comment by M-griffin** [comment]
I just tried Syncterm, Mtelnet, Netrunner,  none of them return the screen perfectly.   Putty works good of course.  And i will update my client.  Maybe when i get sometime i can put together some update's.  This is little stuff so i don't want to waste your time, just something to be aware of.

**Comment by jquast** [comment]
"none of them return the screen perfectly"

so they do, or don't, or have bugs of their own?

anyway i can force a refresh for anything returning, i normally only do that if there were a screen resize change. I'll commit that and you let me know.
