### ISSUE TITLE
msgserve mysteriously stopped accepting https

### ISSUE THREAD

**Issue by jquast** [jquast/x84#279]
```
daily.log.2015-09-13:Sun-09-13 04:03PM INFO   webserve.py:173 https listening on 88.80.6.213:8443/tcp
(...)
daily.log.2015-09-13:Sun-09-13 04:11PM INFO   msgserve.py:219 [defnet] 1 messages served to 3
(...)
```

No other messages were served. No tracebacks were logged to file.

**Comment by jquast** [comment]
still happens, dunno. Used debug logging now on 1984.ws, no errors.

**Comment by haliphax** [comment]
This might be related to your server, and not to msgserve.py -- I don't remember having any issues with x84net. I'm going to set it up again and link up with hellbeard's board. I'll let you know if we see any problems in a few weeks.
