### ISSUE TITLE
irc.py

### ISSUE THREAD

**Issue by jquast** [jquast/x84#28]
Was defualt/irc.py, then default/irc.py.broken, but nearly functional if you want the overhead of twisted python. If I see an irc client committed again, it'd need to be pure python. Callback-based mechanisms like twisted actually provide a very good interface for an irc client!

**Comment by jquast** [comment]
15:30 -!- anonymous [178.211.100.148:51380]
15:30 -!- CONNECtED 2m52s AGO.
15:30 -!- idlE: 43y50w

**Comment by haliphax** [comment]
Trying a rewrite this weekend. So far, I have `pubmsg` and `/quit` working.

**Comment by haliphax** [comment]
I've got everything except the threading bullshit finished, but I'm putting this on pause to finish the message network admin scripts.

**Comment by haliphax** [comment]
I've got a functional, threadless version finished. I'm running some final tests on it today.
