### ISSUE TITLE
add SOCKS5 support for connecting to irc servers via proxy (enhancement)

### ISSUE THREAD

**Issue by funkbuddha** [jquast/x84#282]
I'd like to run x84 as a TOR hidden service but in order to keep the service hidden AND use IRC I'd need to send the traffic over the TOR proxy. I've tried making this work in every way I can come up with but apparently my foo is too weak.

**Comment by tracker1** [comment]
If you set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables to the appropriate proxy settings, does it work?

**Comment by jquast** [comment]
I'm certain theres a way to use a socks proxy, though it may require a code change. We'll have a look soon, thanks for asking!

**Comment by funkbuddha** [comment]
Thanks for taking a look. I'll keep hacking at it as well and see what I can come up with. I setup a dev irc server for some testing.

**Comment by haliphax** [comment]
Python's `irclib` does not support SOCKS5 proxies, though there is a fork which does. Not sure that we'd go with something that isn't on pypi, though...

https://github.com/XayOn/python-irclib

**Comment by haliphax** [comment]
@funkbuddha Have you tried the `HTTP_PROXY` and `HTTPS_PROXY` environment variables that @tracker1 mentioned in his comment above? I know it works for `urlopen`, just not sure if it works with the socket code that `irclib` uses under the covers...
