### ISSUE TITLE
Add CONNECT password support to ircchat.py

### ISSUE THREAD

**Issue by tfaoro** [jquast/x84#284]
Adding the option to specify passwords when connecting to IRC servers would allow x84 users to join Slack channels via their IRC backend. I believe CONNECT passwords are part of the RFC so hopefully it wouldn't be too difficult to add...

**Comment by haliphax** [comment]
It would be fairly trivial, yes. Load password from default.ini, use it as the `password` parameter in the `.connect(...)` call: http://pythonhosted.org/irc/irc.html#irc.client.ServerConnection.connect

Maybe I'll take a crack at it this weekend.
