### ISSUE TITLE
.plan views

### ISSUE THREAD

**Issue by jquast** [jquast/x84#29]
record number of views of .plan files,

show when .plan was last modified.

You could go on and on to create a social network if you really wanted, something small to demonstrate the ability is good enough.

**Comment by haliphax** [comment]
Maybe I'm using an old lc.py version, but when I go to view users' .plan files, they are all sorts of messed up. However many lines there are in the file, that's how many times the entire .plan is repeated.

**Comment by haliphax** [comment]
Gah stupid github buttons.

**Comment by jquast** [comment]
actually, only your lc.py still supports .plan, i just removed it from .profile.
