### ISSUE TITLE
lots of underscores

### ISSUE THREAD

**Issue by deavmi** [jquast/x84#290]
In the `docs/intro.rst` file there are tonnes of underscores (`_`). Are they meant to be there?

**Comment by haliphax** [comment]
Uh, where? https://raw.githubusercontent.com/jquast/x84/master/docs/intro.rst

**Comment by jquast** [comment]
the intro.rst file is in a markup language (ReStructuredText), so yeah they are meant to be there

**Comment by deavmi** [comment]
Weird. On GitHub for Mobile (ForkHub) they appeared. Must of been a bug 
in the renderer. Nevermind then :)

**Comment by haliphax** [comment]
ForkHub is an unofficial app, and I suspect it does not support RST markup.

**Comment by deavmi** [comment]
Ok.
