### ISSUE TITLE
msg editor scrolls line

### ISSUE THREAD

**Issue by billsimon** [jquast/x84#298]
Is there a way to configure the message editor so that when the cursor reaches the end of the line, it moves to the next line and takes the partial word with it, rather than continuing to scroll?

**Comment by jquast** [comment]
sorry, no, I mean, you could edit the code

**Comment by billsimon** [comment]
Haha, no problem, thanks for the quick response :-D

**Comment by jquast** [comment]
sorry :-) this project just officially died today, haha.

Check out https://github.com/NuSkooler/enigma-bbs maybe ;-)
