### ISSUE TITLE
Loading hackernews and weather crashes server

### ISSUE THREAD

**Issue by aroach** [jquast/x84#300]
When I try to run the hackernews script, the server is throwing the following error.  I'm on MacOSX 10.13.4 running Python 2.7.10 in a virtualenv.  This also occurs when running the weather app.

```
Wed-05-16 08:42AM INFO   session.py:674 ashley[ssh-127.0.0.1:52163] runscript 'hackernews'
objc[51392]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[51392]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

**Comment by jquast** [comment]
Not sure if there is anything I can do to help. I do happen to have a Mac, but I mean, I don’t think I can change anything in x84?

https://www.google.com/amp/s/blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/amp/

You can try this with the environment variable. I don’t really like x84’s threading+forking model, I was much younger and inexperienced when I designed it :)

Best wishes and have fun!!!

**Comment by aroach** [comment]
@jquast no worries.  i came across that article as well, and it seemed to explain what's happening. guess I can just run it in linux or docker... :-)

**Comment by aroach** [comment]
FWIW, setting the envvar resolved the issue:

`OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES x84`
