### ISSUE TITLE
problems with openssl

### ISSUE THREAD

**Issue by HACKER-3000** [jquast/x84#301]
While trying to install i got:

   #include <openssl/aes.h>
            ^~~~~~~~~~~~~~~
  compilation terminated.

i have openssl installed, so why does this happen?

**Comment by jquast** [comment]
Try installing openssl-dev package on Debian or unlbuntu—development headers are packaged separately than the libraries

**Comment by haliphax** [comment]
Which Linux distribution are you using?

**Comment by HACKER-3000** [comment]
ubuntu server

**Comment by haliphax** [comment]
Try `libssl-dev`.
