### ISSUE TITLE
python3, asyncio, telnetlib3

### ISSUE THREAD

**Issue by jquast** [jquast/x84#33]
Merge in more reliable and advanced telnet server protocol library https://github.com/jquast/telnetlib3 over the telnet.py forked from miniboa.

re-release x/84 with dual python2.7 and python3.4 support.

**Comment by slyderc** [comment]
Seems like this project has been abandoned.  Any plans to revive the effort?  I'm a Python newbie wanting to dive in with x84 as a base framework for rebirthing a BBS I wrote back in the day, but a 2.x -> 3.x undertaking is way too much for me at present!

**Comment by jquast** [comment]
Yes, I’ve abandoned it for the foreseeable future, thanks for asking.

Not that I’m disinterested, I may pick them up again later, I just haven’t the time in my current employment situation
