### ISSUE TITLE
Really long lines are not wrapped in editors/pagers

### ISSUE THREAD

**Issue by jquast** [jquast/x84#79]
```
                              │ x84/msgserve.py    |  257
                              │+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------                   │ 2 files changed, 144 insertions(+), 130 deletions(-)
                              │
```

You can see here that this message wraps beyond the window edge

**Comment by haliphax** [comment]
Yeah, needs some sort of "break-word" mechanism like CSS. Long URLs are not wrapped, either.

**Comment by jquast** [comment]
we need to support break_long_words in blessed

https://github.com/jquast/blessed/blob/master/blessed/terminal.py#L519
https://github.com/jquast/blessed/blob/master/blessed/sequences.py#L325

You don't want to break something mid-sequence.

**Comment by jquast** [comment]
This has been added to blessed, closing soon.
