### ISSUE TITLE
Refactor msgbase

### ISSUE THREAD

**Issue by tehmaze** [jquast/x84#87]
At the moment msgbase is a mishmash of attributes and DProxy magic, and it lacks a well defined API for creating messages.

While we're at it, we should consider defining (more compliant) standards for follow ups, message dependencies and multi recipient (tags). Also enhancements like #20 would benefit from this, and so would the NNTP server interface.

**Comment by haliphax** [comment]
SQLAlchemy would be awesome, and it has good support for SQLite (though we would need to add a trivial bit of code to enforce referential integrity, which it does not do by default). If SQLAlchemy is used, I'm not sure what else Schematics could bring to the table.
